#  A basic travis.yml boilerplate for Django projects
#
#  The set-up assumes a postgreSQL database.
#  more info at https://gist.github.com/ndarville/3625246 and
#  http://www.lesinskis.com/travis_ci_django.html


language: python

python:
  - "3.5"

cache: pip

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.test"
    - PYTHONPATH="/home/travis/build/arnaudblois/to_do_list"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=1.10.5 DB=postgresql


install:
  - pip install -r requirements/test.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python3 makemigrations --settings=$DJANGO_SETTINGS_MODULE
  - python3 migrate --settings=$DJANGO_SETTINGS_MODULE

script:
  - python3 manage.py test --settings=$DJANGO_SETTINGS_MODULE
