# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170213_1203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('name',)]),
        ),
    ]
